# Create licenseguard group and productworker user using your package manager first.
d /var/lib/license-guard 0750 root licenseguard -
d /etc/license-guard 0750 root licenseguard -
d /usr/lib/license-guard 0755 root root -

